server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka     #配置注册中心url
spring:
  application:
    name: order-client      #指定服务实例名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #数据源
    driver-class-name: com.mysql.jdbc.Driver      #数据库驱动
    url: jdbc:mysql://39.106.154.90:3306/micro_secKill?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8   #Mysql地址
    username: root    #Mysql用户名
    password: root    #Mysql密码
  activemq:
    broker-url: tcp://101.200.57.35:61616
    password: admin
    user: admin
  jms:
    pub-sub-domain: true
management:
  endpoint:
    health:
      show-details: always    #显示详细健康信息
mybatis:
  type-aliases-package: com.shun.entity   #设置实体类的别名
  mapper-locations: classpath:com/shun/mapper/*Mapper.xml    #指定Mybatis的mapper文件位置
logging:
  level:
    com.shun.dao: debug