server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka     #配置注册中心url
spring:
  application:
    name: category-client     #指定服务实例名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.154.90:3306/micro_secKill?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8
    username: root
    password: root
management:
  endpoint:
    health:
      show-details: always      #显示详细健康信息
mybatis:
  type-aliases-package: com.shun.entity
  mapper-locations: classpath:com/shun/maper/*Mapper.xml